### ISSUE TITLE
Add a site icon

### ISSUE THREAD

**Issue by LovelySanta** [AlternativeFFFF/Alt-F4#10]
Currently the site icon is nothing, defaulting to whatever the browser chooses.
![image](https://user-images.githubusercontent.com/26593477/91635196-bb310500-e9f6-11ea-8eac-2cf1ceb9f643.png)

**Comment by ClaudeMetz** [comment]
Yep, I'll contact the person working on this soon to see how it's going. Don't want to time-pressure them too much yet.

**Comment by ClaudeMetz** [comment]
Can someone try and set the favicon on the website to the new logo?

**Comment by Conor12345** [comment]
![image](https://user-images.githubusercontent.com/34628734/91765554-19194480-ebd1-11ea-9636-806574d69864.png)
Picture during testing
