### ISSUE TITLE
Wrong thumbnail being displayed on reddit

### ISSUE THREAD

**Issue by Conor12345** [AlternativeFFFF/Alt-F4#116]
![Screenshot_20200911_140235_com.reddit.frontpage.jpg](https://user-images.githubusercontent.com/34628734/92928786-8467df80-f437-11ea-9926-dd683401f070.jpg)
Also the thumbnail didn't display at all in the discord embed.

**Comment by justchen1369** [comment]
where's this thumbnail from?

**Comment by Conor12345** [comment]
> where's this thumbnail from?
> 

Weirdly, it's the second image from the post... Would expect it to maybe use the first but nope

**Comment by justchen1369** [comment]
and this is on the SEO side, right?

**Comment by Conor12345** [comment]
![Screenshot_20200911_141711_com.discord.jpg](https://user-images.githubusercontent.com/34628734/92930165-9ea2bd00-f439-11ea-89de-9ce275cabc4d.jpg)
Example of the discord embed not detecting the thumbnail

**Comment by justchen1369** [comment]
Any pointers on where to investigate?

**Comment by Conor12345** [comment]
https://www.reddit.com/r/help/comments/1aqd5v/how_does_reddit_select_the_thumbnail_image_of_a/
Seems like embed.ly handles the thumbnail selection by looking for some css and html stuff. Need to research it more but hopefully there is a magic class we can add to the thumbnail to detect it.

**Comment by Conor12345** [comment]
https://support.embed.ly/hc/en-us/articles/204266025-Why-does-Embedly-choose-the-image-that-it-does-?mobile_site=true
Selection criteria used by embed.ly
