### ISSUE TITLE
Fix author formatting

### ISSUE THREAD

**Issue by Conor12345** [AlternativeFFFF/Alt-F4#171]
Issues was raised in discord a few days ago but I forgot to create on here

**Comment by dexteritas** [comment]
<img width="339" alt="Alt-f4_headings" src="https://user-images.githubusercontent.com/19909936/94989875-19ae4d80-0578-11eb-8df9-a45601be48eb.png">

It seems that the format is only working correctly if there is a link at the end of the heading, as in the HTML translation the link of the heading itself is ended before in that case, compare:
```html
<a href="#spidertron-missed-leg-day-lovely_santa" class="anchor" style="text-decoration: none;">Spidertron Missed Leg Day <author>Lovely_Santa</author></a>
```
(author is inside the heading link) to
```html
<a href="#mod-spotlight-spidertron-engineer-robynthedevil" class="anchor" style="text-decoration: none;">Mod Spotlight: </a><a href="https://mods.factorio.com/mod/SpidertronEngineer">Spidertron Engineer</a> <author>Robynthedevil</author>
```
(author is outside the heading link and heading link is ended before the link inside the heading)
Maybe it just needs an HTML post-production step.
