### ISSUE TITLE
Standardisation of some technical terms

### ISSUE THREAD

**Issue by Firerazer** [AlternativeFFFF/Alt-F4#187]
Hey!
I propose that we have a list somewhere that asks/reviews for a given standard on some terms in the submissions.
One example will be today in discord, with the science packs name vs color. In issue 5, we have done Name (color) and this may be the standard and used each time for example.
I am sure there are other terms that would need such standardization, that's why I create this issue

**Comment by Conor12345** [comment]
What's the status of this? Feels like we've done most of the standardization mentioned.
