### ISSUE TITLE
Discord webhook announces new post before it is available

### ISSUE THREAD

**Issue by Foxite** [AlternativeFFFF/Alt-F4#191]
https://discordapp.com/channels/139677590393716737/159197078289907712/761548956282519552

The webhook links to https://alt-f4.blog/ALTF4-7/ which at the time of writing goes to a 404 page.

I noticed vercel has not yet commented on the [commit](https://github.com/AlternativeFFFF/Alt-F4/commit/f113182ea4eac95d4f3e1596c9dc44519bd390b0) (which is on the release branch, incidentally) that added the 7th post. I don't know how the build process works here but that may be important.

**Comment by Conor12345** [comment]
We are having issues with regional caches (we think) due to cloudflare caching a request for Alt-F4 7 before it was released causing it to cache the 404. Tech is working on it atm and hopefully it will be resolved soon.

**Comment by Foxite** [comment]
That seems to be it, as switching to a US-based VPN lets me view the post.

Closing this as it's an external issue.
