### ISSUE TITLE
Timer layout issues

### ISSUE THREAD

**Issue by ClaudeMetz** [AlternativeFFFF/Alt-F4#193]
Currently, the timer we sometimes embed behaves weirdly. If you just put it in, it overlaps with the bottom text. The quick solution was to add a linebreak after it, but that makes it have a big margin on bottom and a smallish one on top. It would be great if we could find a way to have it have the same padding/margin on top and bottom.

**Comment by Conor12345** [comment]
![image](https://user-images.githubusercontent.com/34628734/95023506-5744d080-0675-11eb-943f-b66145f90170.png)
Some weirdness going on here for sure

**Comment by CanadaHonk** [comment]
Timer is supposed to be inline but will probably just make it take a whole line.
