### ISSUE TITLE
Move to self hosting on media server (previously "Switch to vercel for hosting (previously "Stop caching 404 pages")")

### ISSUE THREAD

**Issue by Conor12345** [AlternativeFFFF/Alt-F4#194]
Also need more people to have access to cloudflare

**Comment by justchen1369** [comment]
Is this because cloudfare had a lot of people trying to access unreleased alt-f4 posts?

**Comment by Conor12345** [comment]
> Is this because cloudfare had a lot of people trying to access unreleased alt-f4 posts?

Think so yes. People try to go to a page that isnt released yet, that gets cached then sticks around for like 2 hours.
