### ISSUE TITLE
Small spelling error in README

### ISSUE THREAD

**Issue by MrConorAE** [AlternativeFFFF/Alt-F4#217]
There's a small typo in the README.md file, shown on the Code page.

In the third paragraph (starting with "After coming full circle"), the word "discontinue" is spelt incorrectly as "discontinute".
*(please don't take this badly; I just can't figure out a way to make this sound not aggressive!)*

**Comment by justchen1369** [comment]
fixed with https://github.com/AlternativeFFFF/Alt-F4/commit/7a7d61215345b70f9338ffff56f5f1050d37f16a
