### ISSUE TITLE
Update About page

### ISSUE THREAD

**Issue by DrMagPie** [AlternativeFFFF/Alt-F4#222]
- [ ] Include Wube's Copyright notice [based on](https://discordapp.com/channels/745990677606826005/746687101059203103/764201746548654140)
- [ ] Credit FMMO for hosting site.
- [ ] Credit all the tech people

**Comment by Conor12345** [comment]
Think this is the updated list of tech people, but it probably needs double checking https://discordapp.com/channels/745990677606826005/746687101059203103/755377609071656980
![image](https://user-images.githubusercontent.com/34628734/95654765-22fc6480-0afa-11eb-844d-064d7b029517.png)
**Plus psihius**

**Comment by ClaudeMetz** [comment]
Yeah I'll do this soon, sorry for taking so long.

**Comment by ClaudeMetz** [comment]
Addressed in #229.
