### ISSUE TITLE
Spidertron disappears on short pages

### ISSUE THREAD

**Issue by Nanogamer7** [AlternativeFFFF/Alt-F4#307]
![](https://user-images.githubusercontent.com/45211068/99372556-a0b54c00-28c0-11eb-90e7-77d24cd34a74.png)
*Spidertron under the footer, cut off halfway*

Steps to reproduce:

1. Go on any page, easier on small pages like https://alt-f4.blog/page2/
2. Zoom out until the footer isn't at the bottom of the page anymore
3. Click on spidertron and sendhim further down

Using Firefox Nightly 84.0a1

**Comment by Conor12345** [comment]
Oh this is fun one. I recreated it in chrome too. I suspect its to do with the fact that we don't render spidertron whilst its offscreen for performance reasons.

**Comment by xthexder** [comment]
Whoops.. this is caused by https://github.com/AlternativeFFFF/Alt-F4/pull/290

Spidertron won't draw past the page content to prevent it from resizing the page.
I'll see if I can fix this with` min-height` or a change in the calculation to determine if the window is larger than the content.
