### ISSUE TITLE
Google search console raised issues

### ISSUE THREAD

**Issue by Conor12345** [AlternativeFFFF/Alt-F4#308]
Two issues have been brought up by google search console:

![image](https://user-images.githubusercontent.com/34628734/99435354-ea755500-2907-11eb-9107-8a43018c0e78.png)
https://web.dev/lcp/

![image](https://user-images.githubusercontent.com/34628734/99435393-f5c88080-2907-11eb-9eba-5bb45fc1f750.png)
https://web.dev/cls/

I suspect this is contributing to us not being picked up by google discover.

**Comment by CanadaHonk** [comment]
Can you re-check? Checked Lighthouse (desktop) and stats are looking much better now.
![Lighthouse stats report](https://user-images.githubusercontent.com/19228318/108503424-43101180-72ac-11eb-913c-11211c12326d.png)
