### ISSUE TITLE
Add new graphics to website

### ISSUE THREAD

**Issue by Conor12345** [AlternativeFFFF/Alt-F4#31]
Update website header with new logo

**Comment by Conor12345** [comment]
![testwithlogo](https://user-images.githubusercontent.com/34628734/91596102-8bcdba00-e95c-11ea-8cce-4da2d4c99cac.png)

**Comment by LovelySanta** [comment]
Could be usefull to use the same icon for #10

**Comment by Conor12345** [comment]
Absolutely.
[Alt-F4-LogoPackage.zip](https://github.com/AlternativeFFFF/Alt-F4/files/5145101/Alt-F4-LogoPackage.zip)
