### ISSUE TITLE
Page buttons don't show which page is active

### ISSUE THREAD

**Issue by xthexder** [AlternativeFFFF/Alt-F4#311]
Expected:
![](https://media.discordapp.net/attachments/746687101059203103/778749181756964922/unknown.png)

**Comment by DrMagPie** [comment]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/23652900/99602023-568bb200-2a09-11eb-8978-fc277aea86ab.png">
it happened because .active class was removed in #295

I didn't remember if it is used so still approved.
But still gonna blame @justchen1369 XD (not seriously)
