### ISSUE TITLE
Bad site SEO

### ISSUE THREAD

**Issue by Conor12345** [AlternativeFFFF/Alt-F4#324]
https://forums.factorio.com/viewtopic.php?f=5&t=91567

Better SEO optimization needed somehow. Need an expert in this field to help!

**Comment by CanadaHonk** [comment]
Searching "altf4 factorio" / similar, website gets top and then GitHub repo.
![Screenshot](https://user-images.githubusercontent.com/19228318/107747445-56046e00-6d0f-11eb-957d-7286e3469a09.png)

**Comment by CanadaHonk** [comment]
Same with "altf4 blog" actually:
![Screenshot](https://user-images.githubusercontent.com/19228318/107747710-cb703e80-6d0f-11eb-94c9-cec2d19fd2c1.png)

**Comment by Conor12345** [comment]
Interesting, I think our SEO rankings have just naturally improved since I made this issue.

**Comment by CanadaHonk** [comment]
Yeah I've had the same experience in past projects, as more people visit / search you usually just go up naturally.
