### ISSUE TITLE
Factorio map preview embed

### ISSUE THREAD

**Issue by Conor12345** [AlternativeFFFF/Alt-F4#348]
Okay, big idea here - An embed that lets us have a zoom-able, pan-able map that we control. 

This will probably be our most involved embed since its gonna need a Factorio mod along with a nice way to embed the file. I've seen it done before but they all seem to be old(i.e. no https)/not available to the public.

I've found this mod https://mods.factorio.com/mod/FactorioMaps which appears to do what I want but is outdated,

My idea, use the Alt-F4 team to bring this mod up to date, allowing us to have a super cool embed and give the community the use of this tool back.

Fair warning, I know nothing about making Factorio mods so this one will need to be a team effort :D

**Comment by DrMagPie** [comment]
[FactorioMapsOutput.zip](https://media.alt-f4.blog/fileshare/FactorioMapsOutput.zip)
Output of the mod seam to be broken as well. might be with writing new one from scratch. Using this one as reference.

**Comment by DrMagPie** [comment]
While digging around Found this [mapshot](https://github.com/Palats/mapshot)
[Preview](https://mapshot.palats.xyz/?x=-51.0&y=397.5&z=0.0)

**Comment by Conor12345** [comment]
Probably gonna use a map embed for PR #395 releasing on the 19th March. Will be testing mapshot over the next few days.
