### ISSUE TITLE
Language select to narrow for PT-BR

### ISSUE THREAD

**Issue by Nanogamer7** [AlternativeFFFF/Alt-F4#373]
In the language drop down, the gap on the right side of portuguese is too narrow compared to the rest of the UI
<img width="107" alt="Screenshot 2021-01-14 at 17 05 35" src="https://user-images.githubusercontent.com/45211068/104616853-13596280-568b-11eb-8bd7-8697e166ce00.png">

**Comment by justchen1369** [comment]
hm.

**Comment by mflipe** [comment]
_pt-br_ stands for Brazilian Portuguese, but if you want, you can use just _br_.
You can use:
_br_ - Brazilian Portuguese
_pt_ - Portugal Portuguese (_if needed in the future_)

**Comment by Nanogamer7** [comment]
is there a large difference between brazilian and portugal? Like, comparable to en-gb vs. en-us?

**Comment by mflipe** [comment]
I don't know much about en-gb vs en-us.
Also I don't know enough of pt-pt to say if my translations would be good for them, but I inclined to say that they won't.

One example that I know of is that screen in pt-br is "tela" and in pt-pt is "tela" wich is a word that almost no brazilian ever heard before.

**Comment by DrMagPie** [comment]
I think that we should adhere to i18n iso 3166 alpha-2 standard 
https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

and according to that for Brazil country code should be `BR`

**Comment by Nanogamer7** [comment]
Hmm shouldn't it rather be the language codes 🤔 
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

They don't differenciate between regional variations though

**Comment by mflipe** [comment]
![image](https://user-images.githubusercontent.com/26680197/104791104-3f064680-5778-11eb-8bb1-629dc8900772.png)

**Comment by mflipe** [comment]
![image](https://user-images.githubusercontent.com/26680197/104791153-71b03f00-5778-11eb-89e3-b235a8fa2ac2.png)
