### ISSUE TITLE
Custom SEO plugin / code

### ISSUE THREAD

**Issue by CanadaHonk** [AlternativeFFFF/Alt-F4#414]
Right now we are using [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) which is not really fully optimised for our setup and could have improvements made. Making and using our own custom SEO could would help this issue. Helps #324.

**Comment by DrMagPie** [comment]
There was some work done.
and SEO tags were added manually.

**Comment by Conor12345** [comment]
I think at this point our SEO is probably fine. We've gone from basically not appearing on search results to being top for most reasonable searches so I think this issue can now be closed.
