### ISSUE TITLE
Footer links look bad on some screen sizes

### ISSUE THREAD

**Issue by DrMagPie** [AlternativeFFFF/Alt-F4#52]
![](https://cdn.discordapp.com/attachments/746687101059203103/751093537155579984/unknown.png)

we need to adjust some numbers on style sheets. and test on more screen sizes.

**Comment by Conor12345** [comment]
Need to keep in mind issue #46 as mobile updates may change things on the main site.

**Comment by DrMagPie** [comment]
was fixed together with mobile redesign
